"""Simplified music CD shell. Run with Blender --background --python this_file."""
import bpy
import hashlib
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.name = 'Rhine_Music_CD'
def material(name, color, transmission=0, roughness=.4):
    mat = bpy.data.materials.new(name)
    mat.diffuse_color = (*color, 1)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get('Principled BSDF')
    bsdf.inputs['Base Color'].default_value = (*color, 1)
    bsdf.inputs['Roughness'].default_value = roughness
    bsdf.inputs['Transmission Weight'].default_value = transmission
    bsdf.inputs['IOR'].default_value = 1.46
    return mat
frost = material('Frosted_Polymer', (.96,.94,.90), .9, .42)
edge = material('Ivory_Edges', (.84,.80,.71), .3, .35)
back = material('Optical_Diffuser', (.87,.84,.77), 0, .7)
def box(name, center, dimensions, mat, bevel=.018):
    # Author in the same coordinates as Three.js (X right, Y up, Z front).
    x,y,z = center; w,h,d = dimensions
    bpy.ops.mesh.primitive_cube_add(size=1, location=(x,-z,y))
    obj=bpy.context.object; obj.name=name; obj.dimensions=(w,d,h)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.data.materials.append(mat)
    mod=obj.modifiers.new('Small manufactured edge', 'BEVEL')
    mod.width=bevel; mod.segments=2
    bpy.ops.object.modifier_apply(modifier=mod.name)
    for p in obj.data.polygons: p.use_smooth=True
    mod=obj.modifiers.new('Weighted face normals', 'WEIGHTED_NORMAL')
    mod.keep_sharp=True
    bpy.ops.object.modifier_apply(modifier=mod.name)
    return obj
# 4.3 x 3.7 outer rectangle, a slim vertical spine, no screws or inner machinery.
box('Frosted front cover', (.12,1.85,.105), (4.04,3.7,.045), frost, .015)
box('Plain rear shell', (.12,1.85,-.09), (4.04,3.7,.055), back, .017)
box('Continuous left spine', (-2.02,1.85,0), (.26,3.7,.26), edge, .022)
for name,center,size in [
 ('Top rim',(.12,3.673,0),(4.04,.054,.23)),
 ('Bottom rim',(.12,.027,0),(4.04,.054,.23)),
 ('Right rim',(2.123,1.85,0),(.054,3.6,.23))]:
    box(name,center,size,edge,.012)
# Merge by material to preserve the renderer's fixed instanced batches.
for mat in [frost,edge,back]:
    objs=[o for o in scene.objects if o.type=='MESH' and o.data.materials[0]==mat]
    bpy.ops.object.select_all(action='DESELECT')
    for o in objs:o.select_set(True)
    bpy.context.view_layer.objects.active=objs[0]
    if len(objs)>1: bpy.ops.object.join()
    obj=bpy.context.object; obj.name='Music_CD__'+mat.name
    obj['musicCdShell']=True
    scene.cursor.location=(0,0,0)
    bpy.ops.object.origin_set(type='ORIGIN_CURSOR')
bpy.ops.object.select_all(action='SELECT')
bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'art/music-cd.blend'))
bpy.ops.export_scene.gltf(filepath=str(ROOT/'public/assets/music-cd.glb'), export_format='GLB', use_selection=True, export_apply=True, export_extras=True)
digest = hashlib.sha256((ROOT/'public/assets/music-cd.glb').read_bytes()).hexdigest()[:12]
(ROOT/'src/music-cd-asset.ts').write_text('// Generated by art/build_music_cd.py; changes invalidate the browser asset cache.\nexport const MUSIC_CD_ASSET = \"assets/music-cd.glb?v=' + digest + '\";\n', encoding='utf-8')
print('Music CD shell exported:',len(scene.objects),'meshes; no internal contents')
